language: python
python:
  - "3.4"
  - "3.5"
  - "3.6" # 3.6 development branch

env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11

before_install:
    - pip install pytest
    - export DJANGO_SETTINGS_MODULE=crowdtest.settings
    - export PYTHONPATH=$HOME/builds/WFP-BKK/django-crowd-sso

install:
   -  pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
matrix:
  allow_failures:
    - env: DJANGO=1.8