language: python
python:
  - "3.4"
  - "3.5"
  - "3.6-dev" # 3.6 development branch


before_install:
    - pip install pytest
    - export DJANGO_SETTINGS_MODULE=crowdtest.settings
    - export PYTHONPATH=$HOME/builds/WFP-BKK/django-crowd-sso

# command to install dependencies

install:
  #- pip install -q Django==$DJANGO_VERSION djangorestframework
   -  pip install tox-travis
  #- python setup.py -q install
  # command to run tests
script:
  - tox
