language: python
python:
  - "3.5"

env:
  - DJANGO_VERSION=1.9 DJANGO_SETTINGS_MODULE=crowdtest.settings

before_install:
    - pip install pytest
# command to install dependencies

install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  # command to run tests
script: py.test --verbose
