language: python
python:
  - "3.4"
  - "3.5"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev

env:
  - DJANGO_VERSION=1.8.2

# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  # command to run tests
script: pytest