language: python
python:
  - "3.4"

env:
  - DJANGO_VERSION=1.10

before_install:
    - pip install pytest
    - export DJANGO_SETTINGS_MODULE=crowdtest.settings
    - export PYTHONPATH=$HOME/builds/WFP-BKK/django-crowd-sso
    - export PIP_USE_MIRRORS=true

# command to install dependencies

install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  # command to run tests
script: py.test --verbose
