language: python
python:
  - "3.5"

env:
  - DJANGO_VERSION=1.9
before_install:
    - pip install pytest
# command to install dependencies
install:
  - pip3 install -q Django==$DJANGO_VERSION
  - python3 setup.py -q install
  # command to run tests
script: py.test --verbose
